captainVersion: 4
services:
  $$cap_appname:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - $$cap_appname-app-storage:/rails/storage
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      SELF_HOSTING_ENABLED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: $$cap_secret_key_base
      DB_HOST: $$cap_appname-postgres
      POSTGRES_DB: maybe_production
      POSTGRES_USER: maybe_user
      POSTGRES_PASSWORD: $$cap_postgres_pass
    depends_on:
      $$cap_appname-postgres:
        condition: service_healthy

  $$cap_appname-postgres:
    image: postgres:$$cap_postgres_version
    restart: unless-stopped
    volumes:
      - $$cap_appname-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: maybe_user
      POSTGRES_DB: maybe_production
      POSTGRES_PASSWORD: $$cap_postgres_pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maybe_user -d maybe_production" ]
      interval: 5s
      timeout: 5s
      retries: 5

caproverOneClickApp:
    variables:
        - id: '$$cap_maybe_version'
          label: Maybe version
          defaultValue: '0.1.0-alpha.13'
          description: Check out their Docker page for the valid tags https://github.com/maybe-finance/maybe/pkgs/container/maybe
          validRegex: '\d+(\.\d+){0,2}(-[a-zA-Z0-9]+(\.\d+)?)?'
        - id: $$cap_secret_key_base
          label: Secret Key Base
          description: 'Secret key base'
          defaultValue: $$cap_gen_random_hex(64)
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '16'
          description: Checkout their page for the valid tags https://hub.docker.com/_/postgres
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_pass
          label: Postgres Database Password
          description: 'Password for postgres'
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: |-
            The OS for your personal finances.
        end: |-
            Your Maybe instance is available at http://$$cap_appname.$$cap_root_domain
    displayName: Maybe
    isOfficial: true
    description: The OS for your personal finances.
    documentation: This docker-compose is taken from https://github.com/maybe-finance/maybe/blob/main/docs/hosting/docker.md
